version: '3.8'

services:
  frontend:
    build:
      context: .
    ports:
      - "4200:4200"

  backend:
    build:
      context: .
    ports:
      - "8088:8088"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/caisse-enregistreuse
      SPRING_DATASOURCE_USERNAME: caisse-enregistreuse
      SPRING_DATASOURCE_PASSWORD: ""

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloak
    ports:
      - "9095:8080"
    environment:
      - KEYCLOAK_ADMIN=caisse
      - KEYCLOAK_ADMIN_PASSWORD=caisse
    command:
      - "start-dev"

  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: caisse-enregistreuse
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
